### PR TITLE
Determine address

### PR DESCRIPTION
**Pull request by thiagodelgado111**
## Description

* Adds `ipld-dag-pb` as a dependency
* Adds `createDAGNode` to access controller and manifest creation
* Adds `determineAddress` function to `OrbitDB`

### CODE REVIEW

**Comment by chmanie** [comment]
This is cool. Can you tell me how we could use it from the dApp?

**Comment by thiagodelgado111** [comment]
Like we would do to create a store, passing in all the necessary options. (I'll just remove the `onlyHash` thing for now)

**Comment by chmanie** [comment]
Do we need to adjust anything in the dApp?

**Comment by thiagodelgado111** [comment]
Yes and no. It only copies a feature from upstream but doesn't touch anything else on the API. We still need to update our lockfile and whatnot

**Pull request merged**
